<a href="https://colab.research.google.com/github/MuleHakim/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

LISTS

In [7]:
my_list = [[1,2,3,4,5],[3,4,5,6,8]]
my_list

[[1, 2, 3, 4, 5], [3, 4, 5, 6, 8]]

NUMPY ARRAY

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.56464978, 0.69064476, 0.21895808, 0.06472473],
       [0.44519456, 0.41043587, 0.11994486, 0.9066289 ],
       [0.68778965, 0.35830235, 0.55372324, 0.57324125]])

In [12]:
np2 = np.random.rand(4)
np2

array([0.2431525 , 0.97519127, 0.30709833, 0.47797294])

In [25]:
np1.dtype

dtype('float64')

In [29]:
tensor_2d = torch.randn(7,7)
tensor_2d1 = torch.randn(1,7)

In [30]:
tensor_2d

tensor([[-0.6570, -0.2256, -0.8031, -0.8152, -1.7373,  0.1281,  1.0432],
        [-0.1987, -0.6668, -0.3603, -0.8097, -1.4090,  0.9877,  0.3808],
        [-1.6754, -0.0120, -1.6228, -0.0525,  0.4464,  1.5900, -2.2530],
        [ 1.0163, -0.0845,  1.1547,  0.1850,  1.2729,  1.3681, -1.3511],
        [ 0.0199, -1.6976, -1.1172,  0.8416,  0.4155, -0.2110,  1.1533],
        [ 0.8300, -1.8189,  0.4788, -0.3244,  0.2202, -1.4176, -0.4810],
        [ 0.7020,  1.1694, -1.1352,  0.9739, -1.5771, -0.6015,  0.7938]])

TENSORS

In [28]:
tensor_2d1

tensor([[-0.2497,  0.6779, -1.8550, -0.0398, -0.5664, -1.7786,  0.3427]])

In [31]:
tensor_2d * tensor_2d1

tensor([[ 0.6329, -0.0981, -0.9284,  0.4990,  1.0251, -0.0269, -1.8534],
        [ 0.1914, -0.2899, -0.4165,  0.4957,  0.8314, -0.2072, -0.6766],
        [ 1.6138, -0.0052, -1.8759,  0.0321, -0.2634, -0.3336,  4.0027],
        [-0.9790, -0.0367,  1.3349, -0.1132, -0.7511, -0.2870,  2.4003],
        [-0.0191, -0.7380, -1.2915, -0.5152, -0.2452,  0.0443, -2.0489],
        [-0.7995, -0.7907,  0.5535,  0.1986, -0.1299,  0.2974,  0.8546],
        [-0.6762,  0.5083, -1.3123, -0.5962,  0.9306,  0.1262, -1.4103]])

In [21]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5646, 0.6906, 0.2190, 0.0647],
        [0.4452, 0.4104, 0.1199, 0.9066],
        [0.6878, 0.3583, 0.5537, 0.5732]], dtype=torch.float64)